#!/usr/bin/env bash
#install nginx and config to redirct_me
sudo apt update
sudo apt install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

config_dirct_me="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Abel-alx-github permanent;"

sudo sed -i "s/server_name _;/$config_dirct_me/" /etc/nginx/sites-enabled/default

replace="listen 80 default_server;\nerror_page 404 \/my_error404.html;"

sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_error404.html

echo "https://github.com/Abel-alx-github" | sudo tee /var/www/html/redirect_me


sudo service nginx restart
