#!/usr/bin/env bash
# install haproxy and config to handle two server at back

sudo apt-get -y update
sudo apt-get install -y haproxy

sudo bash -c 'echo -e "
    frontend front
        balance roundrobin
        bind *:80
	mode http
	default_backend back_servers
    backend back_servers
        server 491653-web-01 18.233.67.128:80 check
	server 491653-web-02 100.25.162.166:80 check" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
