#!/usr/bin/env bash
#print bad luck on 4th and bad luck on 8th else best school

i=1
while [[ $i -lt 11 ]]; do
	if [[ $i == 4 ]]; then
		echo "bad luck"
	elif [[ $i == 8 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi
((i++))
done
