#!/usr/bin/env bash
#gives you information about the school file

if test -e "school"; then 
	echo "school file exists"
	if test -s "school"; then
		echo "school file is not empty"
		if test -f "school"; then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
