#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#sed -i "s/^*facebook.com$/8.8.8.8 facebook.com/" /etc/hosts
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/new_hosts
echo "127.0.0.2 localhost" > ~/new_hosts
echo "8.8.8.8 facebook.com" >> ~/new_hosts
cp -f ~/new_hosts /etc/hosts
#sed -i "s/^127.0.0.1$/127.0.0.2/" /etc/hosts
#echo "8.8.8.8 facebook.com" >> /etc/hosts
