#!/usr/bin/env bash
#Write a Bash script that displays all active IPv4 IPs on the machine it’s executed on.
#cat /etc/hosts | grep "^[0-9]" | awk '{print $1}'
awk '/^[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?/ {print $1}' /etc/hosts

#ip addr | awk '/inet / {print $2}' | cut -d/ -f1 """ alternative"""
